### ISSUE TITLE
Question: has the UI changed over the past few week?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [alexjlockwood/ShapeShifter#153]
I remember the demos were accessible via the top overflow menu, and that when I chose a demo, there were 2 vectorDrawables, one on the right of the other, and there was a magic-wand button to automatically create the animation.

Where are those ?

**Comment by alexjlockwood** [comment]
Yeah the UI has changed. Check out this video for a summary.

https://youtu.be/2aq3ljlnQdI

I will announce more details in a few hours here: google.com/+AlexLockwood :)

**Comment by AndroidDeveloperLB** [comment]
Before, when I opened one of the demos, it showed 2 vectors, with markers. Now it doesn't. How come?
I also wanted to show the magic-wand button on this case, to demonstrate how cool this feature is, by using it on the demo, as before...

**Comment by alexjlockwood** [comment]
So I am about to write the announcement right now, but to summarize Roman Nurik and I decided to merge [Android Icon Animator](https://romannurik.github.io/AndroidIconAnimator/) and Shape Shifter into a single web app. :)

All of the functionality that used to exist is still there. But in order to access it you need to create a 'pathData' animation block.

![screen shot 2017-06-19 at 9 59 10 am](https://user-images.githubusercontent.com/1380747/27288932-3fcbebf4-54d6-11e7-94a7-4d8441deb149.png)

At that point, you can click on that 'edit' icon in the top right corner in order to see the three side by side canvases like you saw before.

**Comment by AndroidDeveloperLB** [comment]
I think you meant click and not "create": Click on the red part on your screenshot, and click on Edit, and now I see this:
![image](https://user-images.githubusercontent.com/5357526/27289659-611e0d68-5513-11e7-9761-be703cf09328.png)

Creating a new one will show only a single shape.
Still liked the previous way so that I could show it easily (for them, so that they could try it) for anyone who don't know about vectors how cool it is. Anyway, thanks.

**Comment by alexjlockwood** [comment]
Is there a way you think it could be better? I'm open to suggestions. :)

Creating a new pathData animation block will only show one canvas, yes. It *also* shows this stuff too:
 
<img width="318" alt="screen shot 2017-06-19 at 10 24 05 am" src="https://user-images.githubusercontent.com/1380747/27289881-77568040-54d9-11e7-8f21-38933459c750.png">

The reason why I didn't immediately show three canvases every time you select a path animation block is because that right-most panel takes up a good 300px of the screen's width at least, and there was very little remaining space to show the three canvases side-by-side.

**Comment by AndroidDeveloperLB** [comment]
Well only in the demos, you could go directly to the state I've shown on the screenshot, or a state that there are 2 VectorDrawables, waiting for you to press the magic-wand button :)
This could demonstrate the power of this cool button using minimal steps.

**Comment by AndroidDeveloperLB** [comment]
BTW thank you for this tool. I really hope I can convince people to use it and use more vectors.

**Comment by alexjlockwood** [comment]
I hope so too! :)

Thanks for the suggestion. I'll keep it in mind. I am a little worried that people might miss it as well... going to think of ways to make it more obvious.
