### ISSUE TITLE
AutoAwesome: Subpath unexcepted disappear when fixing

### ISSUE THREAD

**Issue by dalisoft** [alexjlockwood/ShapeShifter#179]
Look at project (saved from online version).

[shapes.zip](https://github.com/alexjlockwood/ShapeShifter/files/1167943/shapes.zip)

And have other issue, when i try to set new ms (between) for path-data, fill, etc. it changes first from field.

**Comment by alexjlockwood** [comment]
The reason the subpath unexpectedly disappears is because the path has a fill type of `nonZero`. Since the AutoFix algorithm reverses the order of subpath points, this means that it could potentially have visible effects on the path if the path is nonZero (see https://www.sitepoint.com/understanding-svg-fill-rule-property/). If you set the path to evenOdd in the ShapeShifter UI I think the issue won't be visible anymore.

Ideally I would fix this issue by writing an algorithm that automatically converts nonZero paths to evenOdd, since evenOdd paths are not affected by the order of the points (i.e. like this one: http://www.freepatentsonline.com/6111587.pdf). But I haven't gotten around to it yet.

> And have other issue, when i try to set new ms (between) for path-data, fill, etc. it changes first from field.

Can you explain this issue a bit more? I'm not sure what you mean. Maybe provide a screenshot?

**Comment by dalisoft** [comment]
I am while building my library i think, if there working solution (your app), if we're can be made this export to SMIL or other lightweight format, we no need other things or library

![recording](https://user-images.githubusercontent.com/3511344/28500608-91ed15f6-6fe4-11e7-8aa3-7c378832a3d4.gif)

**Comment by dalisoft** [comment]
See screenshot, as you see first `startTime` field was changing unexcepted

**Comment by alexjlockwood** [comment]
Ohhh yeah, I'm aware of that but. Thanks for reporting. Definitely annoying and something I intend to fix. 

I don't plan on ever adding support for SMIL as it has been deprecated and don't really want to encourage people to use it as a result. I plan on adding support to export the animation as a CSS keyframe animation, but it is a bit of work since there are so many ways to animate things.

**Comment by dalisoft** [comment]
CSS Animations would be useful, but for morphing there no CSS way i think

**Comment by alexjlockwood** [comment]
There is, actually: https://css-tricks.com/many-tools-shape-morphing/#article-header-id-4

The only thing is it isn't supported by all browsers yet, so you probably wouldn't want to use it for a while. Until then, using a SVG spritesheet is always an option.

**Comment by dalisoft** [comment]
Yes, but i am have no idea about SVG spritesheet

**Comment by dalisoft** [comment]
@alexjlockwood I have working script that replaces SMIL, but very lightweight, [here](https://codepen.io/dalisoft/pen/mMJmxX) demo
