### ISSUE TITLE
Animated SVG import

### ISSUE THREAD

**Issue by JonReyH** [alexjlockwood/ShapeShifter#223]
When animated SVG is imported, currently only first frame is accepted. It would be very useful to convert entire animated SVG file into animated drawable file.

**Comment by alexjlockwood** [comment]
Can you upload an example animated SVG? There are many ways to animate an SVG, so I want to be sure I understand the format you are using.

**Comment by JonReyH** [comment]
Note: Uploaded animated SVG file works fine with Google Chrome browser.
 
[ani-svg.zip](https://github.com/alexjlockwood/ShapeShifter/files/1713948/ani-svg.zip)

**Comment by jantursky** [comment]
Or for example this icon pack that contains also SVG animated icons, also doesn't import animation:

[Weather Icon Pack](https://www.amcharts.com/free-animated-svg-weather-icons/)

Thanks for your answer

**Comment by alexjlockwood** [comment]
I'll definitely consider this. Shape Shifter doesn't currently support this because AnimatedVectorDrawables only support a subset of features supported by animated SVGs. There are also a number of ways to animate an SVG (i.e. spritesheet, javascript, CSS keyframes, SMIL, etc.) so it would probably be a large task to get something reliable working.

**Comment by alexjlockwood** [comment]
I probably won't get around to doing this. There are too many ways to define animated SVGs to support them all... and too many unsupported SVG features that are outside of the scope of this project.
