### ISSUE TITLE
Apply rotation to input/output separate to the animation

### ISSUE THREAD

**Issue by jakearchibald** [alexjlockwood/ShapeShifter#49]
Say I want to animate the elephant to the buffalo, and rotate while doing so. I can apply a rotation to the animation, but that means the elephant and/or buffalo are going to start/end at the wrong rotation.

Instead, I want to:

* Rotate the buffalo 90 degs counter-clockwise
* Adjust the points to make a convincing morphing animation
* Apply a 90 deg rotation to the animation

It's that first bit I can't do, other than editing the SVG in another tool. Is it something ShapeShifter should be able to handle?

**Comment by alexjlockwood** [comment]
Yes, this is something I eventually want to support, but I hadn't filed a bug. Thanks!

BTW, a temporary workaround for now is to add a group transformation directly to the SVG file. For example, if you surround the buffalo SVG path with:

```
<g transform="rotate(90)">
  <path id="buffaloPath" />
</g>
```

Shape Shifter will automatically bake any parent group transforms directly into the path node's command string when the SVG is imported. Not a very user friendly solution, but at least it doesn't require opening up another tool. :)

**Comment by jakearchibald** [comment]
Ohh, great that it handles transforms

**Comment by alexjlockwood** [comment]
Yeah, this would probably be a pretty easy feature to implement since most of the necessary math has already been written... it is mostly just figuring out the best way to expose the option in the UI that I would have to figure out. :)

**Comment by alexjlockwood** [comment]
Idea for later:

Add a `transform()` method to `Path`. The `Path` will record the transform operations in its `CommandMutation`s. On subsequent clones the path will output a transformed version of itself. Should be pretty easy, and would support rotation/scale/translation.

Still not sure where to expose this in the UI though.

**Comment by jakearchibald** [comment]
Yay! Cheers

**Comment by alexjlockwood** [comment]
:)

Here is [a demo](https://youtu.be/K_bDZOCcJ7g) of what I have working right now. Let me know if there is anything I missed!

When the user enters a new rotation value `r`, the following changes are made behind the scenes:

1. The end state SVG's `<path d="...">` node is transformed using `translate(-width/2, -height/2) rotate(-r) translate(width/2, height/2)`. This transformation is baked directly into the path data string.
2. The end state SVG is wrapped in a `<g>` and is transformed using `translate(-width/2, -height/2) rotate(r) translate(width/2, height/2)`. Note that this transformation by `r` degrees offsets the above transformation by `-r` degrees.
3. During the animation, the `<g>`'s transform attribute is animated between `0` and `r` degrees.

The only kind of weird thing is that changing the rotation will often require re-autofixing the SVGs since the position of the input SVGs data points could change dramatically (i.e. in the demo video above when changing the rotation from `0` to `180` degrees).

LMK what you think!

p.s. ShapeShifter has a new, easier-to-remember URL now: https://shapeshifter.design (the old URL still works too).

**Comment by alexjlockwood** [comment]
FYI, just published this yesterday.

**Comment by devahmedshendy** [comment]
@alexjlockwood 
I cannot find the option to do rotation.

I am looking for rotating this 180 degree clockwise, is it possible? or still in development?

![Screen Shot 2020-10-13 at 2 30 48 AM](https://user-images.githubusercontent.com/22206851/95801916-337c2d00-0cfc-11eb-9968-d9adb6d945aa.png)

**Comment by alexjlockwood** [comment]
You can wrap the path in a group and alter the pivot/rotation properties:

<img width="544" alt="Screen Shot 2020-10-12 at 6 08 18 PM" src="https://user-images.githubusercontent.com/1380747/95803846-fbea9200-0cb5-11eb-8e62-30e29469456d.png">

You can view an example by clicking "File --> Demo --> Play/Pause animation"

**Comment by devahmedshendy** [comment]
@alexjlockwood Great, found and I can do rotation now. Thanks.
